theme: jekyll-theme-minimal
title: API + service/worker boilerplate template PHP
description: ğŸ’¡ ğŸ—ï¸ A boilerplate API + service/worker template for PHP
logo: https://raw.githubusercontent.com/GuilhermeStracini/api-service-boilerplate-php/main/logo.png
show_downloads: true
